#!/bin/sh

OSARCHES="${OSARCHES:-linux-amd64 linux-386 darwin-amd64 windows-amd64 windows-386}"

set -o errexit

. make/include/colors.sh
. make/include/versioning.sh

printf "%b==> Building %b\n" "${OK_COLOR}" "${ERROR_COLOR}"

for OSARCH in ${OSARCHES}; do
  export GOOS="${OSARCH%-*}"
  export GOARCH="${OSARCH##*-}"
  if test "${GOOS}" = windows ; then SUFFIX=".exe" ; else SUFFIX="" ; fi
  go build -o "build/${OSARCH}/cf-plugin-backup${SUFFIX}" \
    -ldflags="-X main.version=${ARTIFACT_VERSION}" \
    ./
  cp README.txt LICENSE.* "build/${OSARCH}/"
done

printf "%b" "${NO_COLOR}"
