#!/bin/sh

OSARCHES="${OSARCHES:-linux-amd64 linux-386 darwin-amd64 windows-amd64 windows-386}"

set -o errexit

. make/include/colors.sh
. make/include/versioning.sh

printf "%b==> Disting all%b\n" "${OK_COLOR}" "${NO_COLOR}"

for OSARCH in ${OSARCHES}; do
  rm -rf build/cf-plugin-backup
  mkdir build/cf-plugin-backup
  cp "build/${OSARCH}"/* build/cf-plugin-backup/
  tar czf "${APP_VERSION}.${OSARCH}.tgz" --owner=0 --group=0 --numeric-owner -C build cf-plugin-backup
done
