#!/bin/sh

set -o errexit

. make/include/colors.sh

printf "%b==> Formatting %b\n" "${OK_COLOR}" "${ERROR_COLOR}"
ISSUES=$(mktemp /tmp/XXXXX)

trap "rm -f ${ISSUES}" EXIT

go list -f '{{ .Dir }}' ./... | grep -v /vendor/ | while read DIR; do
    goimports -d -e "${DIR}"/*.go | tee -a "${ISSUES}"
done

printf "%b" "${NO_COLOR}"

! test -s "${ISSUES}"
