#!/bin/sh

set -o errexit

. make/include/colors.sh

printf "%b==> Linting%b\n" "${OK_COLOR}" "${ERROR_COLOR}"

ISSUES=$(mktemp /tmp/XXXXX)

trap "rm -f ${ISSUES}" EXIT

go list -f '{{ .Dir }}' ./... | grep -v /vendor/ | grep -v /mocks/ | while read DIR; do
    golint "${DIR}" | tee -a "${ISSUES}"
done

printf "%b" "${NO_COLOR}"
! test -s "${ISSUES}"
