#!/bin/sh

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

set -o errexit

. make/include/colors.sh

printf "%b==> Installing tools%b\n" "${OK_COLOR}" "${NO_COLOR}"
#Great tools to have, and used in the build file
go get -u golang.org/x/tools/cmd/goimports
go get -u golang.org/x/tools/cmd/cover
go get -u github.com/golang/lint/golint
	
#Tools for the project
go get -u github.com/axw/gocov/gocov
go get -u github.com/AlekSi/gocov-xml